{% set version = "0.11.4" %}

package:
  name: coursera-dl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coursera-dl/coursera-dl-{{ version }}.tar.gz
  sha256: 8366ab3e22c712a3e7d4f944c8763ac6c5111210f73ce14f782d9bc24e2d8204

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - coursera-dl=coursera.coursera_dl:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - beautifulsoup4 >=4.1.3
    - requests >=2.10.0
    - six >=1.5.0
    - urllib3 >=1.10
    - pyasn1 >=0.1.7
    - keyring >=4.0
    - configargparse >=0.12.0
    - attrs ==18.1.0

test:
  imports:
    - coursera
  commands:
    - coursera-dl --help

about:
  home: https://github.com/coursera-dl/coursera-dl
  license: LGPL-3.0
  license_file: LICENSE
  license_family: LGPL
  summary: 'Script for downloading Coursera.org videos and naming them.'
  dev_url: https://github.com/coursera-dl/coursera-dl

extra:
  recipe-maintainers:
    - proinsias
