travis:
  secure:
    BINSTAR_TOKEN: SQG5pZ5+GmRB5aiUdx8wNooDWrRbqrxcSyQPMFGq46666tbu1AKE8CNdGlz16JczCs58SJpeYySa6paoDe4A7ldsXr28slqVyiX4zc2PCmO5xVv1X9mVaaAphERhQngVv6aRaHeNEsV+dk5BGwIlbRMlzA2HtgXo2PZ5c7LsuaIZ7S3FQMdDCVrbeLR/B5VFNlw6Y6AUY5ncZsDfQsrhUjwRjXqdTLUnUa+QK+nWT9GAk3qt/Nb/wUq8N1Zr0/C2+iE9TKXq4JFwK1SKe+DhA4MD4rd8Dx/4cp8XuKTpFy8Mrc2ozG4W8Ef0zyS1Ng0d8yQyA1bA2zevQHAO0OBfrdCDTtxdx8s1+NtK9GpZN7jR6boUHR3ExOOKFyBKKRbfiW7WPxIz9BWNvdFEyXCg4fmm6Nw/pb3jErhx+0uEKFkKVDuZ6l6yg25wvFd1pZq4v+V1OcWLmcHHbAe1xPmxu4w7JIEJ1dsDrKD1oPh7IN3qI6PZoEaMvWRrLzUfhZPSiwM7iGkpJOEYNkYgdE1JUeqcsu0xChp7noaxtrVlsIRrYURkpl9PMDJFTsCWvCLUJJHjhXNARPgM/B7TvYEugpPSb1zDm36GBpZXgb4sZX2ZR6N6VYJFy/jRywCYVXQPk9Uj7g9J/9VA3BxnjQ4b5elmwNoNfEl9oGJYMI3mcLE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
